### PR TITLE
Code styles & more

### PR DESCRIPTION
**Pull request by kevinpapst**
Some "housekeeping", please decide if you want some of them. I added single commits so you could cherry pick single commits if wished.

This PR includes:
- an empty LICENSE file to be filled by @mxgross 
- configuration for php-cs-fixer
- a .gitignore file for kimai bundles to simplify maintainers life
- composer.json was adjusted:
  - proper project name (for registration via packages if wanted)
  - added scripts `composer codestyle` and `composer codestyle-fix`
  - bumped version to 0.2 for the next release

All the other code changes come from running the codestyle fixer via `composer codestyle-fix`.
This aligned the codestyle to be unified across all files.

### CODE REVIEW

**Comment by kevinpapst** [comment]
Whoops, some git magic failed. will cleanup the problems...

**Comment by mxgross** [comment]
> Whoops, some git magic failed. will cleanup the problems...

I think it was my fault, I tried to resolve a merge conflict and it seems like I reverted the route/path changes by accident.

**Comment by kevinpapst** [comment]
Fixed the merge conflict. The code looks good on my end and works.

**Comment by kevinpapst** [comment]
Almost, after your latest push ;-) will merge again

**Comment by mxgross** [comment]
Thanks, I will merge it now. I will see how I can setup my Visual Studio Code to use this codestyle.

**Comment by kevinpapst** [comment]
I am used to this codestyle. My workflow is to use a local pre-commit hook to run `composer codestyle`. If this fails, I cannot push and run `composer codestyle-fix` manually.

**Pull request merged**
