### PR TITLE
Fix cached config

### PR DESCRIPTION
**Pull request by kevinpapst**
See https://github.com/mxgross/EasyBackupBundle/issues/43

Please test, I did not!

### CODE REVIEW

**Comment by mxgross** [comment]
Thanks a lot.

**Comment by kevinpapst** [comment]
As I wrote: I did not test the changes properly, please do so and let me know if there are still issues.

**Comment by mxgross** [comment]
I had to fix the prefix for the settings keys in EasyBackupConfiguration.php, now I receive the latest values. Thanks :)

**Comment by kevinpapst** [comment]
You fixed the wrong place I believe.

You defined `easybackup` here: https://github.com/mxgross/EasyBackupBundle/blob/master/DependencyInjection/Configuration.php#L23

And `easy_backup` in these places:
- https://github.com/mxgross/EasyBackupBundle/blob/master/EventSubscriber/SystemConfigurationSubscriber.php#L35
- https://github.com/mxgross/EasyBackupBundle/blob/master/Configuration/EasyBackupConfiguration.php#L25

You have to use the same key everywhere and please delete the configs from `kimai2_configuration` before testing.

**Comment by mxgross** [comment]
I changed https://github.com/mxgross/EasyBackupBundle/blob/master/DependencyInjection/Configuration.php#L23 also to easy_backup now. Thanks

**Pull request merged**
